[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "astro"
formatter = { command = "prettier", args = ["--parser", "astro"] }
auto-format = true
language-servers = ["astro-ls", "tailwindcss"]

[[language]]
name = "svelte"
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true
language-servers = ["svelteserver", "tailwindcss"]

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
