[language-server.vscode-css-languageserver]
command = "vscode-css-languageserver"
args = ["--stdio"]

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "css"
formatter = { command = "pnpm", args = ["prettier", "--parser", "css"] }
auto-format = true
language-servers = ["vscode-css-languageserver", "tailwindcss"]

[[language]]
name = "astro"
formatter = { command = "pnpm", args = ["prettier", "--parser", "astro"] }
auto-format = true
language-servers = ["astro-ls", "tailwindcss"]

[[language]]
name = "javascript"
formatter = { command = "pnpm", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "pnpm", args = ["prettier", "--parser", "typescript"] }
auto-format = true
